image: ${CI_DOCKER_REGISTRY_NAME}/irhawks/maven:default

stages:
  - build
  - test
  - run
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s /usr/share/maven/ref/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=~/.m2/repository"

cache:
  paths:
    - ~/.m2/repository/
    - target/

build:
  stage: build
  image: ${CI_DOCKER_REGISTRY_NAME}/irhawks/maven:default
  script:
    - whoami
    - ls -alh /usr/share/maven/ref
    - "mvn $MAVEN_CLI_OPTS compile"
    - "echo $MAVEN_CLI_OPTS"

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

run:
  stage: run
  script:
    - mvn $MAVEN_CLI_OPTS package
    - mvn $MAVEN_CLI_OPTS exec:java -Dexec.mainClass="com.example.app.App"

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
